[package]
edition = "2024"
name = "water-spy"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
defmt = "1"
defmt-rtt = "1"
micropb = "0.6"
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }
embassy-executor = "0.9"
embedded-hal-async = "1.0.0"
embedded-hal-bus = "0.3"
embassy-sync = "0.7"
embassy-time = { version = "0.5.0", features = ["generic-queue-64", "defmt-timestamp-uptime"] }
esp-hal = { version = "1.0.0",features = ["esp32s3", "defmt", "unstable"] }
esp-rtos = { version = "0.2",features = ["embassy", "defmt", "esp32s3"] }
esp-println = { version = "0.16.1",features = ["esp32s3", "defmt-espflash"] }
lora-phy = { version = "3.0.1", features = ["lorawan-radio"]}
lorawan-device = { version="0.12.2",features = ["defmt", "default-crypto"] }
static_cell = "2.1.0"
esp-bootloader-esp-idf = { version = "^0.4.0", features = ["defmt", "esp32s3"] }
[profile.release]
debug = 2

[build-dependencies]
embuild = "0.33"
micropb-gen = "0.6.0"